service: well-being-bot

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: oren
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    PLOTLY_TOKEN: ${env:PLOTLY_TOKEN}
    PLOTLY_USER: ${env:PLOTLY_USER}
    ATLAS_USER: ${env:ATLAS_USER}
    ATLAS_PASS: ${env:ATLAS_PASS}
    ATLAS_DB: ${env:ATLAS_DB}
    POST_ADD_LABEL_URL: ${env:POST_ADD_LABEL_URL}
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: 'get-message'
          method: get
      - http:
          path: 'post-message'
          method: post

plugins:
  - serverless-offline
